# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMyFirstTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_myFirstTest(self):
    self.driver.get("https://www.selenium.dev/selenium-ide/")
    self.driver.set_window_size(550, 693)
    self.driver.get("https://www.selenium.dev/selenium-ide/")
    self.driver.find_element(By.LINK_TEXT, "Docs").click()
    assert self.driver.title == "Getting Started · Selenium IDE"
    self.driver.close()
  
