# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMySecondTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mySecondTest(self):
    self.driver.get("https://www.selenium.dev/")
    self.driver.set_window_size(550, 693)
    self.driver.find_element(By.CSS_SELECTOR, ".selenium-ide:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Help").click()
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Need help?"
    self.driver.close()
  
